import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type ChatSessionDocument = ChatSession & Document;

export enum ChatSessionStatus {
    WAITING = 'waiting',
    ACTIVE = 'active',
    ON_HOLD = 'on_hold',
    ENDED = 'ended',
    ABANDONED = 'abandoned',
}

@Schema({ _id: false })
export class ChatVisitorInfo {
    @Prop({ type: Types.ObjectId, ref: 'Customer' })
    customerId?: Types.ObjectId;

    @Prop()
    name?: string;

    @Prop()
    email?: string;

    @Prop()
    phone?: string;

    @Prop()
    ipAddress?: string;

    @Prop()
    userAgent?: string;

    @Prop()
    location?: string;

    @Prop()
    currentPage?: string;

    @Prop({ type: [String], default: [] })
    visitedPages: string[];
}

@Schema({ _id: false })
export class ChatMetrics {
    @Prop({ default: 0 })
    waitTime: number; // seconds until agent response

    @Prop({ default: 0 })
    chatDuration: number; // total seconds

    @Prop({ default: 0 })
    messageCount: number;

    @Prop({ default: 0 })
    agentMessageCount: number;

    @Prop({ default: 0 })
    visitorMessageCount: number;

    @Prop({ default: 0 })
    avgResponseTime: number; // agent average response time in seconds
}

@Schema({ timestamps: true })
export class ChatSession {
    _id: Types.ObjectId;

    @Prop({ required: true, unique: true })
    sessionId: string; // CHAT-2024-000001

    @Prop({ type: ChatVisitorInfo, required: true })
    visitor: ChatVisitorInfo;

    @Prop({
        type: String,
        enum: Object.values(ChatSessionStatus),
        default: ChatSessionStatus.WAITING
    })
    status: ChatSessionStatus;

    @Prop({ type: Types.ObjectId, ref: 'Admin' })
    assignedAgent?: Types.ObjectId;

    @Prop()
    assignedAt?: Date;

    // Queue management
    @Prop({ default: 0 })
    queuePosition: number;

    @Prop({ type: String, enum: ['general', 'sales', 'support', 'billing'] })
    department?: string;

    // Timestamps
    @Prop()
    startedAt?: Date; // When agent joined

    @Prop()
    endedAt?: Date;

    @Prop()
    lastActivityAt?: Date;

    // Pre-chat form data
    @Prop()
    initialMessage?: string;

    @Prop({ type: Types.ObjectId, ref: 'TicketCategory' })
    category?: Types.ObjectId;

    // Metrics
    @Prop({ type: ChatMetrics, default: {} })
    metrics: ChatMetrics;

    // Satisfaction
    @Prop({ type: Number, min: 1, max: 5 })
    rating?: number;

    @Prop()
    ratingFeedback?: string;

    // Conversion to ticket
    @Prop({ type: Types.ObjectId, ref: 'Ticket' })
    convertedToTicket?: Types.ObjectId;

    // Transfer history
    @Prop({
        type: [{
            fromAgent: { type: Types.ObjectId, ref: 'Admin' },
            toAgent: { type: Types.ObjectId, ref: 'Admin' },
            reason: String,
            transferredAt: Date
        }], default: []
    })
    transfers: Array<{
        fromAgent: Types.ObjectId;
        toAgent: Types.ObjectId;
        reason: string;
        transferredAt: Date;
    }>;

    // Tags
    @Prop({ type: [String], default: [] })
    tags: string[];

    // Transcript
    @Prop({ default: false })
    transcriptSent: boolean;

    // Timestamps (auto-generated by Mongoose)
    createdAt: Date;
    updatedAt: Date;

    @Prop()
    transcriptSentAt?: Date;
}

export const ChatSessionSchema = SchemaFactory.createForClass(ChatSession);

// Indexes
ChatSessionSchema.index({ sessionId: 1 }, { unique: true });
ChatSessionSchema.index({ 'visitor.customerId': 1 });
ChatSessionSchema.index({ status: 1, assignedAgent: 1 });
ChatSessionSchema.index({ status: 1, createdAt: 1 });
ChatSessionSchema.index({ department: 1, status: 1 });
ChatSessionSchema.index({ lastActivityAt: 1 });
